# Generated by Django 5.1.2 on 2025-02-20 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_data', models.BinaryField(help_text='Event data pickled')),
                ('status', models.CharField(
                    choices=[('scheduled', 'Scheduled'), ('succeeded', 'Succeeded'), ('failed', 'Failed')],
                    default='scheduled', help_text='Status of the event (scheduled, succeeded, failed)',
                    max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
